// Code generated by protoc-gen-go-cli. DO NOT EDIT.
//00:31:01

package eventstorev1alpha

import (
	cobra "github.com/spf13/cobra"
)

var (
	ClientCmd = &cobra.Command{
		Use:                "client",
		Short:              ``,
		Long:               ``,
		FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
		DisableFlagParsing: true,
	}
)

func init() {
	ClientCmd.AddCommand(ClientPushCmd)
	ClientCmd.AddCommand(ClientFilterCmd)
}
