// Code generated by protoc-gen-go-cli. DO NOT EDIT.

package eventstorev1alpha

import (
	cobra "github.com/spf13/cobra"
	pflag "github.com/spf13/pflag"
	os "os"
)

var (
	ClientCmd = &cobra.Command{
		Use:                "client",
		Short:              ``,
		Long:               ``,
		FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
		DisableFlagParsing: true,
	}
)

var (
	_ClientPushCmdRequest = &PushRequestFlag{PushRequest: new(PushRequest)}
	ClientPushCmd         = &cobra.Command{
		Use:                "-push",
		Short:              ``,
		Long:               ``,
		Run:                runClientPushCmd,
		FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
		DisableFlagParsing: true,
	}
)

func init() {
	ClientCmd.AddCommand(ClientPushCmd)
	_ClientPushCmdRequest.AddFlags(ClientPushCmd.Flags())
	ClientPushCmd.PreRun = func(cmd *cobra.Command, args []string) {
		ClientPushCmd.Flags().Parse(args)
		if ClientPushCmd.Flag("help").Changed {
			ClientPushCmd.Help()
			os.Exit(0)
		}
		_ClientPushCmdRequest.ParseFlags(cmd.Flags(), args)
	}
}

func runClientPushCmd(cmd *cobra.Command, args []string) {
	cmd.Flags().VisitAll(func(f *pflag.Flag) {
		if !f.Changed {
			return
		}
		DefaultConfig.Logger.Info("flag", "name", f.Name, "value", f.Value.String(), "changed", f.Changed)
	})
}

var (
	_ClientFilterCmdRequest = &FilterRequestFlag{FilterRequest: new(FilterRequest)}
	ClientFilterCmd         = &cobra.Command{
		Use:                "-filter",
		Short:              ``,
		Long:               ``,
		Run:                runClientFilterCmd,
		FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
		DisableFlagParsing: true,
	}
)

func init() {
	ClientCmd.AddCommand(ClientFilterCmd)
	_ClientFilterCmdRequest.AddFlags(ClientFilterCmd.Flags())
	ClientFilterCmd.PreRun = func(cmd *cobra.Command, args []string) {
		ClientFilterCmd.Flags().Parse(args)
		if ClientFilterCmd.Flag("help").Changed {
			ClientFilterCmd.Help()
			os.Exit(0)
		}
		_ClientFilterCmdRequest.ParseFlags(cmd.Flags(), args)
	}
}

func runClientFilterCmd(cmd *cobra.Command, args []string) {
	cmd.Flags().VisitAll(func(f *pflag.Flag) {
		if !f.Changed {
			return
		}
		DefaultConfig.Logger.Info("flag", "name", f.Name, "value", f.Value.String(), "changed", f.Changed)
	})
}
