// Code generated by protoc-gen-go-cli. DO NOT EDIT.
//23:40:45

package eventstorev1alpha

// cli name:
//  client
//    Push
//      --aggregates: message
//        --id: message
//        --commands: message
//          --action: message
//            --action: message
//            --revision: message
//            --payload: message
//        --currentSequence: message
//    Filter
//      --queries: message
//        --subjects: message
//          --text: message
//          --wildcard: message
//        --sequence: message
//          --from: message
//          --to: message
//        --createdAt: message
//          --from: message
//          --to: message
//      --limit: uint64
