// Code generated by protoc-gen-go-cli. DO NOT EDIT.
//00:31:01

package eventstorev1alpha

import (
	cobra "github.com/spf13/cobra"
	pflag "github.com/spf13/pflag"
)

var (
	ClientFilterCmd = &cobra.Command{
		Use:                "filter",
		Short:              ``,
		Long:               ``,
		PreRun:             UnmarshalClientFilterRequest,
		Run:                runClientFilterCmd,
		FParseErrWhitelist: cobra.FParseErrWhitelist{UnknownFlags: true},
		DisableFlagParsing: true,
	}
)

func runClientFilterCmd(cmd *cobra.Command, args []string) {
	cmd.Flags().VisitAll(func(f *pflag.Flag) {
		DefaultConfig.Logger.Info("flag", "name", f.Name, "value", f.Value.String(), "changed", f.Changed)
	})
}
